### ISSUE TITLE
Investigate the cfs2taf function in the CalLite Report Tool

### ISSUE THREAD

**Issue by dezidizon** [CentralValleyModeling/callite-report-tool#3]
@hxiedwr reported in [wrims issue #76](https://github.com/CentralValleyModeling/wrims/issues/76) that the cfs2taf function may have a problem. He reported that the summary table from the new CalLite Report Tool is different from the original Report Tool.

**Comment by rma-tom** [comment]
Conferred extensively with @hxiedwr via email about this. Between us we determined that the difference in the summary values in the reports were not due to the cfs2taf conversions, but to problems with time-windowing in the vista-based data retrieval in the original version of the tool. Hao has updated the DSS reads in the wrims report tool in the devops branch of the wrims repo [see PR#81](https://github.com/CentralValleyModeling/wrims/pull/81)
